os:
  - linux

language: generic
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6

before_script:
  - git clone https://github.com/flutter/flutter.git -b stable
  - cd flutter/
  - git checkout v1.22.6
  - ./bin/flutter doctor

script:
  - ./bin/flutter test --coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.pub-cache
