name: fluttils
description: A package that contains utility widgets and functions for Flutter.
version: 4.0.1
repository: https://github.com/beet-software/fluttils

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
