name: fluttils
description: A package that contains utility widgets and functions for Flutter.
version: 1.0.1
author: Enzo Santos
repository: https://github.com/enzo-santos/fluttils

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
